### ISSUE TITLE
python version required for dctap

### ISSUE THREAD

**Issue by tombaker** [dcmi/dctap-python#10]
[pyproject.toml](https://github.com/dcmi/dctap-python/blob/main/pyproject.toml#L22) currently requires Python 3.9, but I'm not at all sure that the version needs to be so recent.

`dctap` can now be installed with pip (see [PyPI project](https://pypi.org/project/dctap/)), it would be good to adjust the version required to the lowest possible.

@nishad Do you have a way to test whether it will work with earlier Python versions?

**Comment by nishad** [comment]
We can configure travis [1] to run tests against multiple python versions [2]. So far integrating a CI tool is much more efficient. Circle CI [3] is an alternative. Both provide free tier for open source projects.

[1] https://travis-ci.org/
[2] https://docs.travis-ci.com/user/languages/python/#specifying-python-versions
[3] https://circleci.com/open-source/

**Comment by nishad** [comment]
Since we use `Data Classes`, we should be safe with Python 3.7+ [1], still we need versions specific tests to claim this.

[1] https://www.python.org/dev/peps/pep-0557/

**Comment by tombaker** [comment]
@nishad I set up a Github Action to test against Python 3.7 and the tests all pass.
