### ISSUE TITLE
Issues with .dctaprc as a config file name

### ISSUE THREAD

**Issue by nishad** [dcmi/dctap-python#11]
`.*rc` files are a standard convention, but using “`.dctaprc`” raises some issues.

- It is a hidden file in NIX OSs as a dotfile, which may be tricky for many users to find or modify, especially within the working directory. In the long run, this implementation can raise a lot of unexpected side effects. 
- Keeping the file extension `yaml` or `yml` helps the text editors to syntax highlight and validate while editing these files.

https://github.com/dcmi/dctap-python/blob/51ad0de01a9ad464c74b414a59eac43c8030cc9b/dctap/config.py#L44

**Comment by tombaker** [comment]
@nishad Can you suggest an alternative filename?

**Comment by nishad** [comment]
I like to call it just `dctap.yaml`, since I prefer `yaml` as the standard extension as per the official recommendation [1]. Our config is structured, so simply calling it dctap will give us more flexibility in future expansions. Another possibility is, making all dctap parsers respect `dctap.yaml`, not just the Python implementation. 

[1] http://yaml.org/faq.html

**Comment by tombaker** [comment]
@nishad 
`dctap.yaml` is the default, but I am now implementing a command-line option, `--hidden`, such that `dctap init --hidden` writes a new config file to `.dctaprc`.

The `dctap read` command, then, would look first for `dctap.yaml` and, if not found, would then look for `.dctaprc`. If neither file were found, it just uses some built-in defaults.

Does that seem like a reasonable approach? Or do you think that even this could cause "unexpected side effects"?

**Comment by tombaker** [comment]
As described above, this has been addressed.
